name: PR Test

on:
  pull_request:
    branches:
      - master
      
jobs:
  PR:
    runs-on: ubuntu-lastest
    
    steps:
      - name: Use Checkout
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build Project
        run: npm run build
      
      - name: Outgoing Webhook - Jandi
        run: curl -X POST https://wh.jandi.com/connect-api/webhook/11671944/19d6ff85f7d4f3edeb7b3cff4780cfe3 -H "Accept: application/vnd.tosslab.jandi-v2+json" -H "Content-Type: application/json" --data-binary '{"body":"요기가 Body","connectColor":"#FAC11B"}'
